/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farmaciaapp.views;

/**
 *
 * @author Lenovo ideapad 330S
 */
public class DBConfigView extends javax.swing.JDialog {

    /**
     * Creates new form DBConfigView
     */
    public DBConfigView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbmConfigAdmin = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtConfigHost = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtConfigName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtConfigUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtConfigPass = new javax.swing.JPasswordField();
        btnConfigSave = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        cbCreate = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración de base de datos");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 0, 10));

        jLabel1.setText("Administrador ");
        jPanel1.add(jLabel1);

        cbmConfigAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MySQL", "Derby", "Derby Embebido" }));
        jPanel1.add(cbmConfigAdmin);

        jLabel2.setText("Servidor");
        jPanel1.add(jLabel2);

        txtConfigHost.setText("localhost:3306");
        txtConfigHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfigHostActionPerformed(evt);
            }
        });
        jPanel1.add(txtConfigHost);

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3);

        txtConfigName.setEditable(false);
        txtConfigName.setText("pharmacy_database");
        txtConfigName.setEnabled(false);
        jPanel1.add(txtConfigName);

        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4);
        jPanel1.add(txtConfigUser);

        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5);
        jPanel1.add(txtConfigPass);

        btnConfigSave.setText("Guardar");

        lblFeedback.setText("Ingrese los datos de conexion");
        lblFeedback.setToolTipText("");

        cbCreate.setSelected(true);
        cbCreate.setText("Crear si no existe");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfigSave))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConfigSave)
                    .addComponent(cbCreate))
                .addGap(18, 18, 18)
                .addComponent(lblFeedback)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfigHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfigHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfigHostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DBConfigView dialog = new DBConfigView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConfigSave;
    public javax.swing.JCheckBox cbCreate;
    public javax.swing.JComboBox<String> cbmConfigAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblFeedback;
    public javax.swing.JTextField txtConfigHost;
    public javax.swing.JTextField txtConfigName;
    public javax.swing.JPasswordField txtConfigPass;
    public javax.swing.JTextField txtConfigUser;
    // End of variables declaration//GEN-END:variables
}
